language: python
python:
  - "3.6"
virtualenv:
  system_site_packages: false
cache: pip
before_install:
    - pip install pep8
script:
    # Run pep8 on all .py files in all subfolders
    # (I ignore "E402: module level import not at top of file"
    # because of use case sys.path.append('..'); import <module>)
    - find . -name \*.py -exec pep8 --ignore=E402 {} +
install:
  - pip install -r requirements.txt
script:
  - python -m pytest sdb/tests/test_*.py -vv